ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
 
-- Crear el usuario
CREATE USER gera1 IDENTIFIED BY "123456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
 
-- Asignar cuota y permisos bÃ¡sicos
ALTER USER gera1 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO gera1;
GRANT "RESOURCE" TO gera1;
ALTER USER gera1 DEFAULT ROLE "RESOURCE";