ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
 
-- Crear el usuario
CREATE USER duoc IDENTIFIED BY "123456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
 
-- Asignar cuota y permisos bÃ¡sicos
ALTER USER duoc QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO duoc;
GRANT "RESOURCE" TO duoc;
ALTER USER duoc DEFAULT ROLE "RESOURCE";